# -*- coding: utf-8 -*-

##### 方式一覧
# 設定なし
NO_SETTING = 0
# 絶対位置決め
ABSOLUTE_POSITION =1
# 相対位置決め（指令位置基準）
RELATIVE_POSITION_BASED_ON_ORDER_POSITION = 2
# 相対位置決め（検出位置基準）
RELATIVE_POSITION_BASED_ON_DETECT_POSITION = 3
# 連続運転（位置制御）
CONTINUES_OPERATION = 7
# ラウンド絶対位置決め
ROUND_ABUSOLUTE_POSITION_ODER = 8
# ラウンド近回り位置決め
ROUND_NEAR_POSITION_ODER = 9
# ラウンドFWD方向絶対位置決め
ROUND_FORWARD_ABUSOLUTE_POSITION_ODER = 10
# ラウンドRVS方向絶対位置決め
ROUND_REVERSE_ABUSOLUTE_POSITION_ODER = 11
# ラウンド絶対押し当て
ROUND_ABUSOLUTE_PRESS = 12
# ラウンド近回り押し当て
ROUND_NEAR_PRESS = 13
# ラウンドFWD方向押し当て
ROUND_FORWARD_PRESS = 14
# ラウンドRVS方向押し当て
ROUND_REBERSE_PRESS = 15
# 連続運転（速度制御）
CONTINUES_OPERATION_WITH_SPEED = 16
# 連続運転（押し当て）
CONTINUES_OPERATION_WITH_PRESS = 17
# 連続運転（トルク）
CONTINUES_OPERATION_WITH_TORQUE = 18
# 絶対位置決め押し当て
ABUSOLUTE_POSITION_PRESS = 20
# 相対位置決め押し当て（指令位置基準）
RELATIVE_POSITION_WITH_ORDER_POSITION = 21
# 相対位置決め押し当て（検出位置基準）
RELATIVE_POSITION_WITH_DETECT_POSITION = 22
